-- Create offsets table
create table if not exists public.offsets (
  id bigint generated by default as identity primary key,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.offsets enable row level security;

-- Policies
create policy "Allow public read access"
  on public.offsets for select
  using (true);

create policy "Allow admin insert access"
  on public.offsets for insert
  with check (auth.jwt() ->> 'email' like 'act@%');

create policy "Allow admin update access"
  on public.offsets for update
  using (auth.jwt() ->> 'email' like 'act@%');
